language: python
services: postgresql
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - export DJANGO_SETTINGS_MODULE=spbu4u_core.settings
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE travis_test;" -U postgres
  - python manage.py migrate
script:
  - python manage.py test
